POST http://127.0.0.1:3000/api/auth/registro
Accept: application/json
Content-Type: application/json

{
    "email": "admin@mail.com",
    "password": "admin321",
    "username": "admin"
}

### Login
POST http://127.0.0.1:3000/api/auth/login
Accept: application/json
Content-Type: application/json

{
    "email": "admin2@mail.com",
    "password": "admin54321"  
}
    
### Perfil     
GET  http://127.0.0.1:3000/api/auth/perfil
Accept: application/json
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwiZW1haWwiOiJhZG1pbjJAbWFpbC5jb20iLCJ0aW1lIjoiMjAyMi0wNy0xOFQxNTo0NjozOS45MTlaIiwiaWF0IjoxNjU4MTU5MTk5LCJleHAiOjE2NTgxNjI3OTl9.6jwtyOdoxtmnWvfBpL8blEFh6BdlWGzhyhRn2VXeJE8
